### ISSUE TITLE
chaosmonkey can not find eligible instances to terminate

### ISSUE THREAD

**Issue by wen15th** [Netflix/chaosmonkey#108]
**Issue Description**

When I tried to terminate instances using this command:
`chaosmonkey terminate my-chaosmonkey-app default`

- "my-chaosmonkey-app" is my application name
- "default" is the account name

I got this error:
```
[57965] 2025/03/09 00:04:03 WARNING: eligible.Instances failed for InstanceGroup{app=my-chaosmonkey-app account=default region= stack= cluster=}: Name 'deployment my-chaosmonkey-app' does not have any labeled or unlabeled matches
[57965] 2025/03/09 00:04:03 No eligible instances in group, nothing to terminate: InstanceGroup{app=my-chaosmonkey-app account=default region= stack= cluster=}
```

Chaosmonkey is running on my macOS, cloud provider is Kubernetes, and the Spinnaker is managed by Halyard on docker.

Here are some information of the deployments:

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/3e8c77e5-f9e8-4fc8-997c-3e07c3aaa883" />

<img width="1273" alt="Image" src="https://github.com/user-attachments/assets/613160b7-d168-4f3d-9832-193f7358b9d5" />

The configuration of the monkey for the application is also valid:

<img width="846" alt="Image" src="https://github.com/user-attachments/assets/c0ba8bde-d36d-4bef-a4a5-d4aa40ca36c6" />

The chaosmonkey.toml:
```
[chaosmonkey]
enabled = true
schedule_enabled = true
leashed = false
accounts = ["default","spinnakerk8s"]
region = "us-west-2"

start_hour = 9      # time during day when starts terminating
end_hour = 15       # time during day when stops terminating

# location of command Chaos Monkey uses for doing terminations
term_path = "./chaosmonkey-terminate.sh"

# cron file that Chaos Monkey writes to each day for scheduling kills
cron_path = "./cron.d/chaosmonkey-schedule"

[database]
host = "127.0.0.1"
name = "chaosmonkey"
user = "root"
encrypted_password = "root"

[spinnaker]
endpoint = "http://127.0.0.1:8084"
```

And information about my Spinnaker:
This is the application:

<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/29c7c5fb-4cd6-4da4-9ff4-12fcc009baf5" />

This is the clusters info:

<img width="1245" alt="Image" src="https://github.com/user-attachments/assets/c5daa57d-ec31-48d4-b89a-6acd5b33d72b" />

This is the pipeline:

<img width="1248" alt="Image" src="https://github.com/user-attachments/assets/ad8d94c6-bdc4-42d3-b02c-751c2ecb05f1" />

This is the Manifest configuration of my pipeline:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chaosmonkey-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-chaosmonkey-app
  template:
    metadata:
      labels:
        app: my-chaosmonkey-app
    spec:
      containers:
        - image: 'wen15th/my-chaosmonkey-app:v1'
          name: my-chaosmonkey-app
          ports:
            - containerPort: 5000
```

I also find two similar issues: 
- https://github.com/spinnaker/spinnaker/issues/3671
- https://github.com/Netflix/chaosmonkey/issues/60
but seems there is no resolution.
